import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

interface OrderConfirmationRequest {
  email: string;
  name: string;
  orderNumber: string;
  productInterest?: string;
  message: string;
}

Deno.serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const { email, name, orderNumber, productInterest, message }: OrderConfirmationRequest = await req.json();

    // Input validation
    if (!email || !name || !orderNumber || !message) {
      return new Response(
        JSON.stringify({ error: "Missing required fields" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return new Response(
        JSON.stringify({ error: "Invalid email format" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate order number format (should match the pattern generated by the database)
    const orderNumberRegex = /^LCI-\d{8}-\d{4}$/;
    if (!orderNumberRegex.test(orderNumber)) {
      return new Response(
        JSON.stringify({ error: "Invalid order number format" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Validate input lengths to prevent abuse
    if (name.length > 100 || email.length > 255 || message.length > 5000) {
      return new Response(
        JSON.stringify({ error: "Input exceeds maximum allowed length" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Verify the order exists in the database to prevent spoofing
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const { data: orderData, error: orderError } = await supabaseClient
      .from("inquiries")
      .select("id, order_number, email")
      .eq("order_number", orderNumber)
      .eq("email", email)
      .maybeSingle();

    if (orderError || !orderData) {
      console.error("Order verification failed:", orderError);
      return new Response(
        JSON.stringify({ error: "Order verification failed" }),
        { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    console.log(`Sending order confirmation to ${email} for order ${orderNumber}`);

    // Sanitize HTML in message to prevent XSS in emails
    const sanitizedMessage = message
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;")
      .replace(/'/g, "&#039;");

    const sanitizedName = name
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");

    const sanitizedProductInterest = productInterest
      ? productInterest.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      : undefined;

    // Send confirmation email to customer
    const customerEmailRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "Lecrafto International <onboarding@resend.dev>",
        to: [email],
        subject: `Order Confirmation - ${orderNumber}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: linear-gradient(135deg, #8B4513 0%, #5C3317 100%); padding: 30px; text-align: center;">
              <h1 style="color: #F5E6D3; margin: 0;">Lecrafto International</h1>
            </div>
            
            <div style="padding: 30px; background: #fff;">
              <h2 style="color: #5C3317;">Thank You for Your Inquiry, ${sanitizedName}!</h2>
              
              <p style="color: #666; line-height: 1.6;">
                We have received your inquiry and our team is reviewing it. You will receive a response within 24-48 hours.
              </p>
              
              <div style="background: #F5E6D3; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <p style="margin: 0; color: #5C3317;"><strong>Order Number:</strong> ${orderNumber}</p>
                ${sanitizedProductInterest ? `<p style="margin: 10px 0 0 0; color: #5C3317;"><strong>Product Interest:</strong> ${sanitizedProductInterest}</p>` : ""}
              </div>
              
              <p style="color: #666; line-height: 1.6;"><strong>Your Message:</strong></p>
              <p style="color: #666; line-height: 1.6; background: #f9f9f9; padding: 15px; border-radius: 8px;">${sanitizedMessage}</p>
              
              <p style="color: #666; line-height: 1.6;">
                You can track your order status anytime at:<br>
                <a href="https://lecrafto.lovable.app/track-order" style="color: #8B4513;">Track Your Order</a>
              </p>
              
              <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
              
              <p style="color: #999; font-size: 12px; text-align: center;">
                Lecrafto International<br>
                1175 E Prashik Chowk, Haripur Road, Goanbhag, Sangli - 416416<br>
                Email: lecraftointernational2@gmail.com
              </p>
            </div>
          </div>
        `,
      }),
    });

    const customerEmailData = await customerEmailRes.json();
    console.log("Customer email sent:", customerEmailData);

    // Send notification to admin
    const adminEmailRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${RESEND_API_KEY}`,
      },
      body: JSON.stringify({
        from: "Lecrafto International <onboarding@resend.dev>",
        to: ["sumitjadhav7226@gmail.com"],
        subject: `New Order Inquiry - ${orderNumber}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #5C3317;">New Order Inquiry Received</h2>
            <div style="background: #f9f9f9; padding: 20px; border-radius: 8px;">
              <p><strong>Order Number:</strong> ${orderNumber}</p>
              <p><strong>Customer Name:</strong> ${sanitizedName}</p>
              <p><strong>Email:</strong> ${email}</p>
              ${sanitizedProductInterest ? `<p><strong>Product Interest:</strong> ${sanitizedProductInterest}</p>` : ""}
              <p><strong>Message:</strong></p>
              <p style="background: #fff; padding: 15px; border-radius: 8px;">${sanitizedMessage}</p>
            </div>
            <p style="margin-top: 20px;">
              <a href="https://lecrafto.lovable.app/admin" style="background: #8B4513; color: #fff; padding: 10px 20px; text-decoration: none; border-radius: 5px;">View in Admin Panel</a>
            </p>
          </div>
        `,
      }),
    });

    const adminEmailData = await adminEmailRes.json();
    console.log("Admin email sent:", adminEmailData);

    return new Response(JSON.stringify({ success: true, orderNumber }), {
      status: 200,
      headers: { "Content-Type": "application/json", ...corsHeaders },
    });
  } catch (error: any) {
    console.error("Error in send-order-confirmation function:", error);
    return new Response(
      JSON.stringify({ error: "An unexpected error occurred" }),
      {
        status: 500,
        headers: { "Content-Type": "application/json", ...corsHeaders },
      }
    );
  }
});
